config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

    def index
        @kittens = Kitten.all
        respond_to do |format|
            format.json{ render json: @kittens }
        end
    end

    def new
        @kitten = Kitten.new
    end

    def create
        @kitten = Kitten.new(kitten_params)
        if @kitten.save
            flash[:success] = "Congrats, you've made a new fur-rend!"
            redirect_to kittens_path
        else
            flash[:warning] = "There was a problem saving your kitten :("
            redirect_to new_kitten_path
        end
    end

    def show
        @kitten = Kitten.find(params[:id])

        respond_to do |format|
            format.json{ render json: @kitten }
        end
    end

    def edit
        @kitten = Kitten.find(params[:id])
    end

    def update
        @kitten = Kitten.find(params[:id])

        if @kitten.update(kitten_params)
            flash[:success] = "Congrats, you updated your kitten!"
            redirect_to kittens_path
        else
            flash[:warning] = "Something went wrong :("
        end
    end

    def destroy
        @kitten = Kitten.find(params[:id])
        @kitten.destroy
        redirect_to kittens_path
    end

    private

        def kitten_params
            params.require(:kitten).permit(:name, :age, :cuteness, :softness)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |f| %>
    <%= f.label(:name, "Name:") %>
    <%= f.text_field :name %>
    <br>
    <%= f.label(:age, "Age:") %>
    <%= f.text_field :age %>
    <br>
    <%= f.label(:cuteness, "Cuteness:") %>
    <%= f.text_field :cuteness %>
    <br>
    <%= f.label(:softness, "Softness:") %>
    <%= f.text_field :softness %>
    <br>
    <%= f.submit "Submit" %>
<% end %>

app/views/kittens/edit.html.erb
Edit your Kitten:

<%= render "form" %>

app/views/kittens/index.html.erb
Hello, welcome to Kitten builder.

Here are all the kittens:
<br>
<ul>
    <% @kittens.each do |k| %>
        <li><%= k.name %> | <%= link_to "Edit", edit_kitten_path(k.id) %> | <%= link_to 'Delete', k, method: :delete, data: { confirm: 'Are you sure?' } %></li>
    <% end %>
</ul>

app/views/kittens/new.html.erb
Make a new Kitten: 
<br>

<%= render "form" %>

app/views/kittens/show.html.erb
This is kitten <%= @kitten.id %>
<br>
Their name is <%= @kitten.name %>
<br>
Softness: <%= @kitten.softness %>/10
<br>
Cuteness: <%= @kitten.cuteness %>/10
<br>
<%= link_to "Edit", edit_kitten_path(@kitten.id) %> | <%= link_to 'Delete', @kitten, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>